### ISSUE TITLE
Download questions

### ISSUE THREAD

**Issue by phexic** [ibm-aur-nlp/PubLayNet#1]
Great job，thank you for sharing such large-scale document data. However，the speed which i download these datasets is very slow. And, it often disconnected downloads, is there any other way to get these datasets?

**Comment by zhxgj** [comment]
@phexic thanks for your interest. We will look into this issue and solve it asap.

**Comment by phexic** [comment]
@zhxgj Great!

**Comment by zhxgj** [comment]
@phexic we tested a few geographic regions and got decent downloading speed from Box. Can you please let us know which geographic region are you downloading the data from?

**Comment by phexic** [comment]
@phexic Maybe the reason I'm in China

**Comment by zhxgj** [comment]
@phexic Em, maybe Box does not well in China. Let me try to work out a solution for you.

**Comment by phexic** [comment]
Oh, Wow! thanks a million.  
Will you public the pre-training models about  document layout?

**Comment by zhxgj** [comment]
> @zhxgj Oh, Wow! thanks a million.
> Will you public the pre-training models about document layout?

@phexic This is a great suggestion. I will follow up with our legal team regarding releasing the pre-trained model and maybe the training config file.

**Comment by shreyansh05s** [comment]
> > @zhxgj Oh, Wow! thanks a million.
> > Will you public the pre-training models about document layout?
> 
> @phexic This is a great suggestion. I will follow up with our legal team regarding releasing the pre-trained model and maybe the training config file.

@zhxgj Hi, any news from your legal team whether you can release the pre-trained models?

**Comment by zhxgj** [comment]
Hi @phexic The data has been migrated to IBM DAX platform. I think the download should be more stable now. Please see the instructions in README
