### ISSUE TITLE
Dataset format on IBM Developer

### ISSUE THREAD

**Issue by r-zip** [ibm-aur-nlp/PubLayNet#11]
Hi,

First, thanks for moving your dataset off of box.com. Their interface was not very user-friendly.

The dataset format listed on the IBM Developer page does not match the contents of the downloaded archive. The images appear to all be JPEGs, not PNGs.

Could you please request that the dataset format be updated, or (even better due to JPEG compression artifacts) upload PNGs?

**Comment by zhxgj** [comment]
Hi @r-zip Thanks for notifying us about this error. I will make the changes asap.

**Comment by r-zip** [comment]
It looks like this has been fixed. Closing.
