### ISSUE TITLE
instruction about training on my own dataset

### ISSUE THREAD

**Issue by DaoDaoDao123** [ibm-aur-nlp/PubLayNet#12]
Hi,

Thanks for sharing the useful dataset and pre-trained model. 

Is the model trained on Detectron or Detectron2? I wonder if you could provide any detailed instruction about the fine-tuning on my dataset based on the pre-trained model.

Thank you.

**Comment by zhxgj** [comment]
The model was trained on Detectron. The instructions are already given [here](https://github.com/ibm-aur-nlp/PubLayNet/blob/master/pre-trained-models/README.md)
