### ISSUE TITLE
Download speed of this dataset is very slow from India

### ISSUE THREAD

**Issue by ajoymondal** [ibm-aur-nlp/PubLayNet#2]
Thank you for sharing large scale lay out analysis document dataset.  The download speed for this dataset is very slow from India. Sometimes, it often disconnected downloads. Is there any other way to download the dataset?

**Comment by zhxgj** [comment]
Thanks @ajoymondal for reporting this issue. We were also told the speed is slow in China. We are seeking other venues to host the data. We will try to address this issue asap

**Comment by zhxgj** [comment]
Hi @ajoymondal The data has been migrated to IBM DAX platform. I think the download should be more stable now. Please see the instructions in README

**Comment by ajoymondal** [comment]
Hi Zhxgi,

Thank you very much for your help.

Thanks and Regards
Ajoy
