### ISSUE TITLE
Problem with example.tar.gz.

### ISSUE THREAD

**Issue by prameshbajra** [ibm-aur-nlp/PubLayNet#21]
The link mentioned in the notebook downloads a broken/corrupted file.
```
fname = 'examples.tar.gz'
url = 'http://s3.us-south.cloud-object-storage.appdomain.cloud/dax-assets-dev/dax-publaynet/1.0.0/' + fname
r = requests.get(url)
open(fname , 'wb').write(r.content)
```

**Comment by prameshbajra** [comment]
This link should work fine, I guess:
https://dax.cdn.appdomain.cloud/dax-publaynet/1.0.0/examples.tar.gz

**Comment by zhxgj** [comment]
@prameshbajra Thanks. We migrated the data to a new place, but forgot to modify the link in the notebook. Sorry about that. I will fix it now.

**Comment by dwalton76** [comment]
@zhxgj the https://dax.cdn.appdomain.cloud/dax-publaynet/1.0.0/examples.tar.gz link no longer works. Is there a new location for this file?

**Comment by dwalton76** [comment]
Figured it out...should be https://dax-cdn.cdn.appdomain.cloud/dax-publaynet/1.0.0/examples.tar.gz
