### ISSUE TITLE
Cannot access the competition website anymore.

### ISSUE THREAD

**Issue by buptxiaofeng** [ibm-aur-nlp/PubLayNet#43]
The dataset does not contains test.json and the competition website is not working. Is there any method to use the test data, so that I can compare the performance with the teams joined the competition?

**Comment by ajjimeno** [comment]
Thanks for the interest in our work. We are sorting out the test set and
will be back to you soon. Sorry for any inconvenience.

  Antonio

**Comment by ajjimeno** [comment]
The test set has been released.
