### ISSUE TITLE
Download the dataset on command line

### ISSUE THREAD

**Issue by snavavf** [ibm-aur-nlp/PubLayNet#5]
Nice paper and thanks for releasing the PubLayNet dataset!
Is there a way to download the dataset on command line? (instead of using webpage browsers)

Cheers.

**Comment by zhxgj** [comment]
Hi @snavavf someone else also requested this feature, but currently it is not supported by Box. For now, I would suggest to use vnc to open a browser and download the data. We are pushing our legal team to allow us to host the data somewhere else that supports aws S3 API.

**Comment by dice89** [comment]
@snavavf VNC worked fine for me just follow this tutorial: https://medium.com/@Arafat./graphical-user-interface-using-vnc-with-amazon-ec2-instances-549d9c0969c5

**Comment by zhxgj** [comment]
Hi @dice89 The data has been migrated to IBM DAX platform, which supports command line download.
