### ISSUE TITLE
License terms of the PubLayNet dataset

### ISSUE THREAD

**Issue by snavavf** [ibm-aur-nlp/PubLayNet#7]
Hi, the document images are from the commercial use collection of PMC OA.
Then what are the license terms of the PubLayNet dataset? 
Is the whole dataset also allowed for commercial purposes?

Thanks a lot!

**Comment by ajjimeno** [comment]
PMC OA is distributed by the US NIH/National Library of Medicine (NLM) under a Creative Commons license. We are distributing derivative work from the PMC OA collection under a specific license as described in this repository. The derivative work includes among other things images generated from the PDF documents and the location of document layout components using the generated images as reference, so it is not what the NLM is distributing with PMC OA. The license under which we distribute the derivative work should be quite permissive, but please check with your company legal team.
