### ISSUE TITLE
Test.json?

### ISSUE THREAD

**Issue by dice89** [ibm-aur-nlp/PubLayNet#9]
Hi first of all thank you for this great dataset :-) Just one minor question, do you plan to also upload the test.json? I couldn't find it in the box.

**Comment by zhxgj** [comment]
Hi @dice89 Thanks for your interest. We are not going to release the test ground truth because we want to keep it for a competition in the future. But we are setting up a service for people to submit their results and get evaluated. We will announce the update once the service is ready.

**Comment by dice89** [comment]
Perfect! Thanks for the answer! Looking forward to the challenge.
